# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              Idea Conservatory
logo:               \images\logo.png
description:        Ideas, Objects, Creativity
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://ideaconservatory.org' # The base hostname & protocol for your site
twitter:            https://twitter.com/joshuageorgem
facebook:           https://www.facebook.com/joshuageorgem
instagram:          https://www.instagram.com/joshuageorgem
markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  joshua:
    name:     Joshua Mathew
    bio:      Connects dots for a living. Mining objects, for humans to program.
    gravatar: https://secure.gravatar.com/avatar/b08b86c9fd7f09a69763746e649c2ce9
    email:    joshuageorgem@gmail.com
    website:  http://ideaconservatory.org
    github:   https://github.com/joshuageorgem
    twitter:  https://twitter.com/joshuageorgem